{"name": "test_006", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 2) == 4", "trace": "self = <test_02.Test object at 0x10687b7c0>\n\n    @allure.story(\"测试用例3\")\n    def test_006(self):\n        \"\"\"\n        assert 语句通过断言来触发异常\n        :return:\n        \"\"\"\n        print(\"这是一条异常用例\")\n        a = 1\n        b = 2\n>       assert a + b == 4\nE       assert (1 + 2) == 4\n\ntestcase/test_02.py:39: AssertionError"}, "description": "\n        assert 语句通过断言来触发异常\n        :return:\n        ", "attachments": [{"name": "stdout", "source": "f85583ce-b8af-4bbc-b561-69abaec9e84d-attachment.txt", "type": "text/plain"}], "start": 1714035566211, "stop": 1714035566212, "uuid": "8c4a5db3-dd22-4733-81c4-04b2040056bc", "historyId": "a438539e98b14a17fe8afec997eb7a95", "testCaseId": "a438539e98b14a17fe8afec997eb7a95", "fullName": "testcase.test_02.Test#test_006", "labels": [{"name": "feature", "value": "模块2"}, {"name": "story", "value": "测试用例3"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_02"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "Haiyangxie.local"}, {"name": "thread", "value": "12228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_02"}]}